services:
  dev-vnc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5901:5901"
    environment:
      - VNC_USER=developer
      - VNC_PASSWORD=devpass123
      - DISPLAY=:1
    volumes:
      - ./scripts:/entrypoint.d
      - ./home:/home
    healthcheck:
      test: ["CMD", "pgrep", "-f", "Xvnc"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"
